version: '3.8'

services:
  # MongoDB - Database for storing application data
  mongodb:
    image: mongo:latest
    container_name: chlann-mongodb-prod
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - chlann-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis - For caching and pub/sub messaging
  redis:
    image: redis:alpine
    container_name: chlann-redis-prod
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - chlann-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # MinIO - S3-compatible storage for media files
  minio:
    image: minio/minio
    container_name: chlann-minio-prod
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - chlann-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Media Service - Handles media uploads, processing, and retrieval
  media-service:
    build:
      context: ../backend/media-service
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: chlann-media-service-prod
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/media?authSource=admin
      - REDIS_URI=redis://:${REDIS_PASSWORD}@redis:6379
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET=media
    depends_on:
      - mongodb
      - redis
      - minio
    networks:
      - chlann-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Search Service - Handles search functionality
  search-service:
    build:
      context: ../backend/search-service
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: chlann-search-service-prod
    restart: always
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/search?authSource=admin
      - REDIS_URI=redis://:${REDIS_PASSWORD}@redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - chlann-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx - Reverse proxy for the services
  nginx:
    image: nginx:alpine
    container_name: chlann-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - media-service
      - search-service
    networks:
      - chlann-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  chlann-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  minio_data:
